linters-settings:
  lll:
    line-length: 200

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - revive
    - stylecheck
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - depguard
    - misspell
    - lll
    - unparam
    - dogsled
    # - funlen
    - gochecknoinits
    # - gocritic
    # - godox
    - nakedret
    - prealloc
    - whitespace
    # - wsl
    - exportloopref
  disable:
    - noctx
    - scopelint
    - gochecknoglobals
    - errorlint

  disable-all: false
  presets:
    - bugs
    - unused
  fast: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - dupl