version: '3'

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config.example.yaml:/config.yaml
      

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email=<your-email> --agree-tos --no-eff-email --staging -d <your-domain-name>