version: '3'

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    environment:
      - TINSHOP_HOST=tinshop.example.com
      - TINSHOP_PROTOCOL=https
      - TINSHOP_NAME=TinShop
      - TINSHOP_REVERSEPROXY=true
      - TINSHOP_WELCOMEMESSAGE=Welcome to TinShop!
      - TINSHOP_NOWELCOMEMESSAGE=false
      - TINSHOP_DEBUG_NFS=false
      - TINSHOP_DEBUG_NOSECURITY=false
      - TINSHOP_DEBUG_TICKET=false
      - TINSHOP_NSP_CHECKVERIFIED=true
      - TINSHOP_SOURCES_DIRECTORIES=/games
      - TINSHOP_SECURITY_WHITELIST=0000000000000000000000000000000000000000000000000000000000000000 1111111111111111111111111111111111111111111111111111111111111111
    ports:
      - 3000:3000
    volumes:
      - /media/switch:/games
      

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email=<your-email> --agree-tos --no-eff-email --staging -d <your-domain-name>