name: ginkgo

on: 
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37.0.2
        with:
          files: |
            go.*
            **/*.go

      - name: Verify Go Modules Setup
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go mod verify
      
      - run: go mod tidy && git diff --exit-code go.mod go.sum
        if: steps.changed-files.outputs.any_changed == 'true'

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37.0.2
        with:
          files: |
            go.*
            **/*.go

      - run: go vet ./...
      
      - name: Install ginkgo
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go get github.com/onsi/ginkgo/v2/ginkgo

      - name: Print out Ginkgo version
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go run github.com/onsi/ginkgo/v2/ginkgo version

      - name: Launch tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --race --trace -cover