name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.9.2
        with:
          files: |
            go.*
            **/*.go

      - name: golangci-lint
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.53.3